package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/rhvdpols/gql/leaderboards/graph/model"
)

// FindGameByID is the resolver for the findGameByID field.
func (r *entityResolver) FindGameByID(ctx context.Context, id string) (*model.Game, error) {
	if id == "1" {
		return &model.Game{
			ID:          "1",
			Leaderboard: r.LeaderBoards[0],
		}, nil

	} else {
		return &model.Game{
			ID:          "2",
			Leaderboard: r.LeaderBoards[1],
		}, nil
	}
}

// FindPlayerByID is the resolver for the findPlayerByID field.
func (r *entityResolver) FindPlayerByID(ctx context.Context, id string) (*model.Player, error) {
	return &model.Player{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
