// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Player struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Profile *Profile `json:"profile"`
}

func (Player) IsEntity() {}

type Profile struct {
	Bio string `json:"bio"`
}

type Query struct {
}
