// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Leaderboard *Leaderboard `json:"leaderboard"`
}

type Leaderboard struct {
	Rankings []*Ranking `json:"rankings,omitempty"`
}

type Player struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Profile  *Profile   `json:"profile"`
	Rankings []*Ranking `json:"rankings,omitempty"`
}

type Profile struct {
	Bio string `json:"bio"`
}

type Query struct {
}

type Ranking struct {
	Rank   int     `json:"rank"`
	Player *Player `json:"player"`
	Points int     `json:"points"`
}
