package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/rhvdpols/gql/players/graph/model"
)

// FindPlayerByID is the resolver for the findPlayerByID field.
func (r *entityResolver) FindPlayerByID(ctx context.Context, id string) (*model.Player, error) {
	for _, player := range r.Players {
		if player.ID == id {
			return player, nil
		}
	}

	return nil, fmt.Errorf("player with id %s not found", id)
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
