package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/rhvdpols/gql/players/graph/model"
)

// ListPlayers is the resolver for the listPlayers field.
func (r *queryResolver) ListPlayers(ctx context.Context) ([]*model.Player, error) {
	return r.Players, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
