// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (Game) IsEntity() {}

type GameState struct {
	Ranking []*Player `json:"ranking"`
}

type Player struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Query struct {
}

type Subscription struct {
}
