package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/rhvdpols/gql/games/graph/model"
)

// FindGameByID is the resolver for the findGameByID field.
func (r *entityResolver) FindGameByID(ctx context.Context, id string) (*model.Game, error) {
	panic(fmt.Errorf("not implemented: FindGameByID - findGameByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
