package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/rhvdpols/gql/games/graph/model"
)

// ListGames is the resolver for the listGames field.
func (r *queryResolver) ListGames(ctx context.Context) ([]*model.Game, error) {
	return r.Games, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
