// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	ID          string       `json:"id"`
	Leaderboard *Leaderboard `json:"leaderboard"`
}

func (Game) IsEntity() {}

type Leaderboard struct {
	Rankings []*Ranking `json:"rankings,omitempty"`
}

type Player struct {
	ID string `json:"id"`
}

func (Player) IsEntity() {}

type Query struct {
}

type Ranking struct {
	Rank   int     `json:"rank"`
	Player *Player `json:"player"`
	Points int     `json:"points"`
}
